project:
  type: book
  output-dir: docs

book:
  title: "Workshop"
  author: "Aaron E. Jaime y Yahir Cabrera"
  date: "05/22/2025"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "**Sección 1** - Organización de proyectos metagenómicos"
      chapters:
      - 1Ordendedatos.qmd
      - 2Planificaciondeproyectos.qmd
      - 3DatosdeNCBI.qmd
    - part: "**Sección 2** - Introducción a línea de comandos"
      chapters:
      - 4IntroduccionnavigationShell.qmd
      - 5Operacionesyexploraciondefastq.qmd
      - 6Redireccion.qmd
      - 7Buclesscriptsdescarga.qmd
      - 8Organizacionproyecto.qmd
    - part: "**Sección 3** - Primeros pasos con R Studio"  
      chapters:
      - 9IntroduccionRStudio.qmd
      - 10Tiposdedatos.qmd
      - 11Graficandoconggplot.qmd
    - part: "**Sección 4** - Procesamiento y visualización de datos metagenómicos"
      chapters:
      - 12Iniciandomiproyectometagenomico.qmd
      - 13Controldecalidad.qmd
      - 14Filtraciondedatosdesecuenciacion.qmd
      - 15Ensamblemetagenomico.qmd
      - 16Binningmetagenomico.qmd
      - 17Asignaciontaxonomica.qmd
      - 18Exploraciondetaxonomiaconr.qmd
      - 19Exploraciondediversidad.qmd
      - 20Analisistaxonomico.qmd
      - 21Otrosrecursos.qmd
      
    
  # Information
  repo-url: https://iscb-rsg-mexico.github.io/Taller_Metagenomica/ # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "rsgMexico.jpeg" # icono de la pagina en pestana


format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-wrap: true
    message: false
    warning: false
    fig-height: 8
    fig-width: 8
    fig-align: "center"
    freeze: false  # Desactivar congelamiento
    grid: 
      body-width: 1200px
      sidebar-width: 250px
      margin-width: 200px
      gutter-width: 0.8em
    fontsize: 14 pt
      

editor: visual

